export const REDUCER_CONSTANTS ={
    LOGIN:'AUTH_LOGIN',
    LOGOUT:'AUTH_LOGOUT',
    GET_CUSTOMER_BEGIN:"GET_CUSTOMER_BEGIN",
    GET_CUSTOMER_SUCCESS:'GET_CUSTOMER_SUCCESS',
    GET_CUSTOMER_FAILURE:'GET_CUSTOMER_FAILURE',
    GET_TRANSACTION_BEGIN:"GET_TRANSACTION_BEGIN",
    GET_TRANSACTION_HISTORY_SUCCESS:'GET_TRANSACTION_HISTORY_FAILURE',
    GET_TRANSACTION_HISTORY_FAILURE:'GET_CUSTOMER_HISTORY_FAILURE',
    RESTRICTED_RECEIVER_BY_NAME:'VALIDATE_RECEIVER_BY_NAME',
    RESTRICTED_RECEIVER_BY_ID:'RESTRICTED_RECEIVER_BY_ID',
    RECEIVER_NOT_FOUND:'RECEIVER_NOT_FOUND',
    RECEIVER_FOUND:'RECEIVER_FOUND',
    SENDER_NOT_FOUND:'SENDER_NOT_FOUND',
    SENDER_FOUND:'SENDER_FOUND',
    INVALID_AMOUNT_TRUE:'INVALID_AMOUNT_TRUE',
    INVALID_AMOUNT_FALSE:'INVALID_AMOUNT_FALSE',
    BANK_API_SUCCESS:'BANK_API_SUCCESS',
    BANK_API_FAILURE:'BANK_API_FAILURE',
    INSERTION_SUCCESS:'INSERTION_SUCCESS',
    INSERTION_FAILURE:'INSERTION_FAILURE'

}